# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'BRCA Exchange' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for BRCA Exchange
  pod 'Firebase/Messaging'

  # for testing push notifications in the simulator
  pod 'SimulatorRemoteNotifications', '~> 0.0.3'

  target 'BRCAMobileTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
