# Customize this file, documentation can be found here:
# https://docs.fastlane.tools/actions/
# All available actions: https://docs.fastlane.tools/actions
# can also be listed using the `fastlane actions` command

# If you want to automatically update fastlane if a new version is available:
# update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "2.66.2"

# default_platform :ios


# ---------------------------------------------------------------------------------------------------------------------
# --- iOS
# ---------------------------------------------------------------------------------------------------------------------

platform :ios do
  before_all do
    ENV["SLACK_URL"] = "https://hooks.slack.com/services/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"
    # cocoapods # FAISAL: commented out b/c cocoapods makes me nervous
    # carthage
  end

  desc "Runs all the tests"
  lane :test do
    scan
  end

  desc "Just build it"
  lane :build do
    match(type: "appstore", git_url: "git@github.com:falquaddoomi/BRCAMobile-secrets.git")

    gym(
        scheme: "BRCAMobile Release",
        workspace: "ios/BRCAMobile.xcworkspace",
        output_directory: "fastlane/ios_build"
    )
  end

  desc "Submit a new Beta Build to Apple TestFlight"
  desc "This will also make sure the profile is up to date"
  lane :beta do
    match(type: "appstore", git_url: "git@github.com:falquaddoomi/BRCAMobile-secrets.git")

    gym(
      scheme: "BRCAMobile Release",
      workspace: "ios/BRCAMobile.xcworkspace",
      output_directory: "fastlane/ios_build"
    )

    pilot(skip_waiting_for_build_processing: true)

    # sh "your_script.sh"
    # You can also use other beta testing services here (run `fastlane actions`)
  end

  desc "Deploy a new version to the App Store"
  lane :release do
    # match(type: "appstore")
    # snapshot
    gym
    # deliver(force: true)
    # frameit
  end

  # You can define as many lanes as you want

  after_all do |lane|
    # This block is called, only if the executed lane was successful

    # slack(
    #   message: "Successfully deployed new App Update."
    # )
  end

  error do |lane, exception|
    # slack(
    #   message: exception.message,
    #   success: false
    # )
  end
end


# ---------------------------------------------------------------------------------------------------------------------
# --- android
# ---------------------------------------------------------------------------------------------------------------------

platform :android do
  before_all do
    ENV["SLACK_URL"] = "https://hooks.slack.com/services/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"
  end

  desc "Runs all the tests"
  lane :test do
    gradle(task: "test", project_dir: "android")
  end

  desc "Just build it"
  lane :build do
    gradle(task: "assembleRelease", project_dir: "android")
  end

  desc "Submit a new Alpha Build to Play Store"
  lane :alpha do
    gradle(task: "assembleRelease", project_dir: "android")
    supply(track: "alpha", apk: "android/app/build/outputs/apk/app-release.apk") # Upload the APK to the Play Store (alpha)
  end

  desc "Submit a new Beta Build to Crashlytics Beta"
  lane :beta do
    gradle(task: "assembleRelease", project_dir: "android")
    supply(track: "beta", apk: "android/app/build/outputs/apk/app-release.apk") # Upload the APK to the Play Store (alpha)
  end

  desc "Deploy a new version to the Google Play"
  lane :deploy do
    gradle(task: "assembleRelease", project_dir: "android")
    supply
  end

  # You can define as many lanes as you want

  after_all do |lane|
    # This block is called, only if the executed lane was successful

    # slack(
    #   message: "Successfully deployed new App Update."
    # )
  end

  error do |lane, exception|
    # slack(
    #   message: exception.message,
    #   success: false
    # )
  end
end


# ------------------------------------------------------------------------------------------------
# More information about multiple platforms in fastlane: https://docs.fastlane.tools/advanced/#control-configuration-by-lane-and-by-platform
# All available actions: https://docs.fastlane.tools/actions
# ------------------------------------------------------------------------------------------------
# fastlane reports which actions are used. No personal data is recorded.
# Learn more at https://docs.fastlane.tools/#metrics
# ------------------------------------------------------------------------------------------------
